- name: Configure network and routing on CentOS/RHEL
  hosts: all
  become: yes
  vars:
    iface_name: enp0s3
    iface_ip: 172.16.3.254
    iface_netmask: 255.255.255.0
    routes:
      - dest: 172.16.1.0/24
        via: 10.0.2.3
      - dest: 172.16.2.0/24
        via: 10.0.2.4
    masquerade_iface: enp0s8

  tasks:

    - name: Ensure routes are present
      ansible.builtin.command: ip route add {{ item.dest }} via {{ item.via }}
      loop: "{{ routes }}"
      ignore_errors: yes # si la route existe deja

    
    - name: Restart enp0s3 interface only
      ansible.builtin.command: ifdown {{ iface_name }} && ifup {{ iface_name }}
      ignore_errors: yes

